### ISSUE TITLE
“Show list” and “Back to map” should always float at the bottom of the screen on mobile

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#150] opened 2023-04-29 12:45 UTC
“Show list” and “Back to map” should always float at the bottom of the screen on mobile, even if the list of programs is long and continues to scroll, the option "Back to map" should always be floating at the bottom of the screen. 
This will make navigation much easier and more intuitive. 80% of users are on mobile phones, so this is a very important issue to fix, as navigation is a critical part of the experience. 

The same applies to "Show list" button - it should always float at the bottom, while currently it is often covered by browser controls, and it is really hard to scroll to it, as scrolling moved the map, and not the page. 

Current situation: 
https://user-images.githubusercontent.com/18451161/235303094-63db8f20-7458-4db3-9ba0-6b8b45698153.MP4

Expected look: 
![IMG_855B5A319AC7-1](https://user-images.githubusercontent.com/18451161/235303134-d671390e-f56c-4bac-ad5b-8a51609eddb0.jpeg)

**Comment by Ardnived** [comment] 2023-04-29 13:25
This is a duplicate of https://github.com/sydevs/Atlas/issues/134

This is a Safari-specific problem, because Safari is not accurately reporting to us the useable part of the screen. The buttons you mentioned are floated, but I believe they are hidden behind the address bar.

**Closed by Ardnived** 2023-04-29 13:25 UTC
